language: go
go: 1.12.x
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - g++-6
      - gcc-6
      - glide
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/vendor
    - $GOPATH/src
    - $GOPATH/pkg

before_cache:
  - find $HOME/.glide/cache -name ORIG_HEAD -exec rm {} \;
  - rm -rf $GOPATH/src/github.com/coinexchain/dex/*
  - rm -rf $GOPATH/pkg/**/github.com/coinexchain/dex

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN

before_install:
  - export GO111MODULE=on
  - export GOROOT=$(go env GOROOT)
  - export CXX="g++-6" CC="gcc-6"
  - export PATH=$PATH:$HOME/gopath/bin

install:
  - cd -
  - go mod tidy
  - go mod vendor
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ./scripts/check.sh

notifications:
  email:
    on_success: change
    on_failure: always